services:
  backend:
    build:
      context: backend
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    volumes:
      - ./.env:/code/.env

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - frontnet

networks:
  backnet:
  frontnet:

secrets:
  db-password:
    file: db/password.txt